### PR TITLE
servers/create - updated UI

### PR DESCRIPTION
**Pull request by IceToast**
Updated the servers/create page to a more mordern UI. The ressource selection is now a list of cards to select from.

Screenshot of UI:
image

### CODE REVIEW

**Comment by 1day2die** [comment]
Hot

**Comment by anondev-sudo** [comment]
Update also page that will see userd when server is created (Servers tab in the menu) to similar cards

**Comment by IceToast** [comment]
> Update also page that will see users when server is created (Servers tab in the menu) to similar cards

That's a whole different topic and has nothing to do with this pr.
This pr is focused on server creation only

**Comment by anondev-sudo** [comment]
The design should be the same. Also how will server creation page look when you have more than 5 plans, will there be max 5 plans in a row? And how does it look on phone?

**Comment by IceToast** [comment]
The design do not have to be the same as they serve a much different need of information. If you want it to be same, go for it.

Why would there be a limit. They would overflow to the next row. 

This project is not mobile focused at all, but using grids like that will make the whole app very responsive. On mobile it would be exactly the same but not as many cards in a row obviously...

**Comment by anondev-sudo** [comment]
Like it, but can you make similiar cards with available information for servers page? Like the fontawesome icons, smaller cards

**Comment by anondev-sudo** [comment]
Also it would be nice to include node, location, egg, nest on the card too. On the original page it is.
image

**Comment by IceToast** [comment]
Dude I told you already, that is not the point of this PR. make an issue or make it yourself!

**Comment by anondev-sudo** [comment]
Why removing things that were there before?

**Comment by IceToast** [comment]
> Why removing things that were there before?

What the hell are you talking?! I redesigned the UI. Stop demanding me to do anything you want to have, do it yourself.

There is not information being removed. It's just way more modern.

Now stop commenting on this PR!

**Comment by anondev-sudo** [comment]
So where is chose egg, node and nest on the card? You removed it

**Comment by IceToast** [comment]
> So where is chose egg, node and nest on the card? You removed it

Are you stupid? Its right there, just like before. Node, Software/Game (aka. Nest) and Specification (aka. Egg)...

**Review by anondev-sudo — COMMENTED** [review]
It was removed. Selected nest, egg and node is not showed on the product cards. You can see it just in the select form elements.

**Comment by IceToast** [comment]
> It was removed. Selected nest, egg and node is not showed on the product cards. You can see it just in the select form elements.

What you are talking about was the "checkout summary" on the right side, which gave a summary of the whole configuration, to check before buying. 

This PR is about the "resource plan"-selection, which i redesigned to be a modern card selection. 
As you can tell (from the screenshot above) you can see all the configuration information without the need of a summary.
I removed the summary on the right side, as it breaks the centered design of this redesign.

I tried rearranging the UI components, but that didn't help. Thinking about why the summary was there in the first place i decided to remove it as it does not serve any needs. All the information is visible at one glance.

**Comment by anondev-sudo** [comment]
#294 is not implemented in this PR, this includes just redesign of server create page, servers page is not redesigned

**Comment by IceToast** [comment]
> #294 is not implemented in this PR, this includes just redesign of server create page, servers page is not redesigned

This comment is not related to this PR but the issue you are talking about, please keep it to the mentioned issue

**Pull request merged**
