### PR TITLE
PaymentController improvents

### PR DESCRIPTION
**Pull request by anondev-sudo**
Adds description, disable that user needs to share their address with owner, and other to paypal payment request

### CODE REVIEW

**Comment by AVMG20** [comment]
Has this been tested by you?

**Comment by anondev-sudo** [comment]
I sadly don't have PayPal balance to test it, but I think that it will work. I got it from paypal api docs

**Comment by RamonRobben** [comment]
> I sadly don't have PayPal balance to test it, but I think that it will work. I got it from paypal api docs

You should test it with PayPal Sandbox. If it works in sandbox mode you have a 99% chance that it will work in normal mode aswell. Unless you fill in the wrong API key / secret.

**Comment by AVMG20** [comment]
> I sadly don't have PayPal balance to test it, but I think that it will work. I got it from paypal api docs

You can test it like Ramon says with the Paypal sanbox API tokens, and set your .ENV to local

**Pull request closed without merging**
