### PR TITLE
Add payer object

### PR DESCRIPTION
**Pull request by anondev-sudo**
I think that it will be nice if the `payer` object will be added to the PayPal API request, so you can know the user who purchased the credits when browsing payments on the PayPal dashboard.

### CODE REVIEW

**Comment by anondev-sudo** [comment]
@AVMG20 Will you merge this?

**Comment by anondev-sudo** [comment]
@AVMG20

**Comment by anondev-sudo** [comment]
Why this was not added to update?

**Comment by anondev-sudo** [comment]
Can you check this @1day2die ?

**Comment by IceToast** [comment]
I'm sorry, this PR needs to be redone completely. The stripe integration changed the DB and the routes to be much more modular.
Please redo it for the new integration and PR it again. Or create an issue to let others do it.

**Pull request closed without merging**
