### PR TITLE
Fix allocation limit

### PR DESCRIPTION
**Pull request by j122j**
Use product's allocation limit instead of 1.

### CODE REVIEW

**Comment by ok236449** [comment]
This issue was created 26 days ago and it still wasn't fixed in the "prerelease" version. Propably only in development. It shouldn't be hard, it is propably just a typo because all the other variables are used correctly when ordering a server. Why is there such a big delay?

**Comment by RamonRobben** [comment]
> This issue was created 26 days ago and it still wasn't fixed in the "prerelease" version. Propably only in development. It shouldn't be hard, it is propably just a typo because all the other variables are used correctly when ordering a server. Why is there such a big delay?

I mean the fix has been merged to Development. There just hasn't been a release in a while due to various circumstances.
The goal is to have a stable development branch before creating a release.

**Comment by ok236449** [comment]
Ok then. And do you think the release will come out let's say in the next month? Any idea if it will be a full release, or a prerelease something like v0.5?

**Comment by RamonRobben** [comment]
@ok236449 Yeah should be this week maybe. Depends on how much time the original creator has to test all the merges etc.
Yeah other payment methods, and server add-ons are the more major additions that are not yet planned. Mainly because everyone has a different opinion on payment method / provider. I think Stripe was in the planning but I am unsure wether it was scrapped or not. For add-ons it has not yet been planned since its a quite big addition.

**Pull request merged**
