### PR TITLE
Added Support & Status tab added

### PR DESCRIPTION
**Pull request by SneakyHub**
Arc Support Added
Google Analytics Support Added
Status Page added

I also added a bit of documentation to the .env file to show off different parts easier.

### CODE REVIEW

**Review by SneakyHub — COMMENTED** [review]
ignore this

**Comment by SneakyHub** [comment]
The only one you need to care about is this.

https://github.com/ControlPanel-gg/dashboard/pull/107/commits/e3479d8baf08e6e643e0abe41dfd5c65b37f6be3

**Comment by anondev-sudo** [comment]
You can also add website to menu 
```
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{{env('WEBSITE_URL')}}" class="nav-link" target="__blank">Website</a>
            </li>
```

**Comment by anondev-sudo** [comment]
And maybe make that it wont be showed when you havent filled those enviromental variables. As when someone dont want it or dont use arc/google analytics what will be the scripts for?

**Comment by SneakyHub** [comment]
> 
> 
> And maybe make that it wont be showed when you havent filled those enviromental variables. As when someone dont want it or dont use arc/google analytics what will be the scripts for?

Hey, I'm busy developing on SneakyHub, this is what we use. I didn't have to make it so it's configurable for .env but I did so others can use it. If you or someone else wants to neaten it up. Look at what I did. It works for us over at SneakyHub. So just go from there. But anyways, I've made a few more fixes for allocations and so on for our network and I might PR them to the development branch of dashboard if this request makes it through.

**Pull request closed without merging**
