### PR TITLE
Show Server price per Hour / per Month

### PR DESCRIPTION
**Pull request by 1day2die**
Comming from Issue :  https://github.com/ControlPanel-gg/dashboard/issues/196

### CODE REVIEW

**Comment by 1day2die** [comment]
image

**Comment by 1day2die** [comment]
> Please use proper indentation.
> Also I would keep the structure of the table the same so title left (in this case Price per month or hour) and on the right the value.
> 
> So like:
> Price per hour: 100 credits
> Price per month: 3750 credits

Ah okay.
I did it like this because the card would become so long otherwise

**Comment by j122j** [comment]
What if the hourly credit usage was here?
Right/below in the same box, or in the separate box on the right, there is space there.

image

**Comment by 1day2die** [comment]
> What if the hourly credit usage was here?
> Right/below in the same box, or in the separate box on the right, there is space there.
> 
> image

That space is already used by this Pull Request

https://github.com/ControlPanel-gg/dashboard/pull/197


See

**Comment by anondev-sudo** [comment]
Good idea

**Comment by anondev-sudo** [comment]
Also there is configuration credit display name, so you should use it

**Comment by anondev-sudo** [comment]
Also why is server description not displayed in server card?

**Comment by 1day2die** [comment]
> Also there is configuration credit display name, so you should use it

Oh snap, of course.

>Also why is server description not displayed in server card?

dunno. it never was

**Comment by anondev-sudo** [comment]
You can add description table row too

**Comment by AVMG20** [comment]
looks good, we do have plans on changing the server listing soon. so it might not even see daylight in main branch (not sure when si i merge it ) Good job, thanks for both pull request 👍

**Pull request merged**
