### PR TITLE
Just some visual ones

### PR DESCRIPTION
**Pull request by anondev-sudo**

### CODE REVIEW

**Comment by anondev-sudo** [comment]
image
To prevent from pressing it more times ...

**Review by nickdevnl — CHANGES_REQUESTED** [review]
This change doesnt work now there are 2 create buttons

**Review by nickdevnl — APPROVED** [review]
jk

**Comment by IceToast** [comment]
Reworked the whole create server UI. #315 
This PR would be obsolete then

**Comment by 1day2die** [comment]
Thanks for this anon, however as IceToast stated already this has been reworked a whole lot :)

**Comment by anondev-sudo** [comment]
> image To prevent from pressing it more times ...

Make sure to add there this too

**Comment by 1day2die** [comment]
@IceToast  hes got a point

**Pull request closed without merging**
