### PR TITLE
Replace pterodactyl link with dashboard link

### PR DESCRIPTION
**Pull request by anondev-sudo**
Replace pterodactyl link with dashboard link in table and add pterodactyl link on show user page

### CODE REVIEW

**Comment by AVMG20** [comment]
Uhm, Why? This button already brings you to our show page. Now the name and button bring you to our show? I don't understand why you want to make this change. I think it's very convenient to have the ability to go to the show page of either ptero or dashboard while browsing on the index page.
image

**Comment by anondev-sudo** [comment]
Because it's easier when I click on the link.

There is problem that I can't use ID or email from pterodactyl in API request. So when I click on the user name, I get pterodactyl ID, but on pterodactyl there is not dashboard id. 

Option to use pterodactyl and dashboard IDs in API will solve my issue.

**Comment by AVMG20** [comment]
> Because it's easier when I click on the link.
> 
> There is problem that I can't use ID or email from pterodactyl in API request. So when I click on the user name, I get pterodactyl ID, but on pterodactyl there is not dashboard id.
> 
> Option to use pterodactyl and dashboard IDs in API will solve my issue.

You can click on the eye button, see the user profile page and copy the Ptero ID from there. this has always been there and changing the link does have nothing to do with this issue besides removing useful functionality.

**Comment by anondev-sudo** [comment]
Ok

**Pull request closed without merging**
