### PR TITLE
Partners and discounts

### PR DESCRIPTION
**Pull request by ok236449**
This big PR contains:
 - fixes to admin overview page - I found out the caching did not really work outside of the artisan testing environment - the tables showed only zeroes.
 - new possibility to make partnerships - Partners tab gives you the ability to give them and their referrals discounts and limit their referral commission in a way that does not affect the other users. - almost like described in this [feature request #253](https://github.com/ControlPanel-gg/dashboard/issues/253)
 - fixes for the admin users table - mainly sorting by last_seen column - [Issue #563](https://github.com/ControlPanel-gg/dashboard/issues/563)
 - added user name to payments table - [Feature request #546](https://github.com/ControlPanel-gg/dashboard/issues/546)
 - fix for a typo that was giving incorrect redirections or 404s

image
image
image

PS: The discounts need good testing! I was unable to test using Stripe, because I was unable to get the Stripe test environment working. Using PayPal the discounts work well.

### CODE REVIEW

**Comment by sybetjeh** [comment]
damn this looks dope ngl

**Comment by Tix-Hosting** [comment]
@ok236449 
Does the Partner Feature mean, that he gets the Commission every time, even when the Same User is buying for a second and or third time and so on? Like Described here? https://github.com/ControlPanel-gg/dashboard/issues/459#issuecomment-1158115620

**Comment by ok236449** [comment]
With this, you can offer someone a discount for purchasing credits, they may advertise your host in return. The commission thing overides the default value that is available for everyone. (If you offer for example a 15% commission in the referral system, you may want to lower this for the partner, cuz you are effectively paying him to advertise you.) I am not really sure, but I think it does that for every purchase (didn´t change it, so if CP did that for only the first one, it is the same, I changed just the amount(percentage) value.

**Comment by 1day2die** [comment]
Currently it's only on the first time of credits purchase afaik

**Comment by ok236449** [comment]
Latest changes:
 - made everything stable and fully tested (hopefully)
 - Yearly tax and income overview in /admin/overview
 - commission switch as listed in #459 - THIS NEEDS TO BE TESTED - I am unable to do so (both payment method sandboxes aren´t working for me).
 
 Homepage now shows you some info about the referral system:
image
That also goes together with partnerships, if the user has a parthership, it looks like this:
image

**Comment by Tix-Hosting** [comment]
Wow this looks amazing!

I hope this will be released in 0.8.4 very very soon!

**Comment by Tix-Hosting** [comment]
@ok236449 
Did you test the Following:

500 Error after Payment page when 100% Discount is given? 

Maybe also grey out the Payment Providers and Change the Button to "Order for Free" or something

Or is it not Intended to give a Partner a 100% Discount? If not, this would be a Great addition :)

But anyways, it looks really amazing as it is right now!

**Comment by SneakyHub** [comment]
This looks great! Would be nice to see some statistics from an admin point of view showing how many referrals each partner got on the admin page but honestly well done! great work! Can't wait to see this implemented.

**Comment by AGuyNamedJens** [comment]
Hello,

Not to discourage anyone here but we have **stopped** producing new versions since v0.8.3 as the entire development team is now focused towards releasing Version 1.0. It's a big rewrite, costing a lot of time which is focused on a new and better user-friendly panel, as well as letting 3rd party developers add new features easier without affecting the main panel, using packages.

In case you haven't joined yet, be sure to join the Discord server which explains more about this.
For anyone interested, feel free to use this Pull Request (by fetching from [their repo](https://github.com/ok236449/dashboard/tree/Partners-and-discounts) you want these features in your own panel. Version 0.8.3 will only receive security patches.
For @ok236449 feel free to contribute this new feature to Version 1.0 if you'd like.

For the record; we're not discontinuing ControlPanel, we're just no longer accepting and creating new features as we've shifted our focus on the rewrite which also supports the newest version of PHP (8.1)

**Comment by IceToast** [comment]
> Hello,
> 
> Not to discourage anyone here but we have **stopped** producing new versions since v0.8.3 as the entire development team is now focused towards releasing Version 1.0. It's a big rewrite, costing a lot of time which is focused on a new and better user-friendly panel, as well as letting 3rd party developers add new features easier without affecting the main panel, using packages.
> 
> In case you haven't joined yet, be sure to join the Discord server which explains more about this. For anyone interested, feel free to use this Pull Request (by fetching from [their repo](https://github.com/ok236449/dashboard/tree/Partners-and-discounts) you want these features in your own panel. Version 0.8.3 will only receive security patches. For @ok236449 feel free to contribute this new feature to Version 1.0 if you'd like.
> 
> For the record; we're not discontinuing ControlPanel, we're just no longer accepting and creating new features as we've shifted our focus on the rewrite which also supports the newest version of PHP (8.1)

I do have to intervene on that. Yes the the core team (mainly 1Day2Die and AVMG) have decided to discontinue v0.8 in favor for the new rewrite v1. It might not be the correct place to talk about this, but you brought this up and at some point someone has to talk about it.

There are a few things that are off and lead to the poor development speed of V1:
- Private repository (AVMG) -> no connection the the organisation "ControlPanel-gg" on Github
- No development guides on how to do things in V1
- No demo of V1
- No documentation of V1
- No overview of what has been fundamentally changed to favor this rewrite instead of improving v0.8
- Low activity rate

Afterall CP has been transformed from a privately used software to a community driven open source project. I personally dislike to discontinue v0.8 as long as V1 is nowhere near being able to use in production.
What this PR (and others) show is that the community clearly seek to improve CP with new features and bugfixes even though a rewrite has been announced. 

Short digression:
A rewrite has been started to have core functionality be implemented in a better more professional way (using suitable libs i.e.). It also serves the updated dependencies like Laravel 9 and Support for upcomming PHP Versions. It's main selling point is the new frontend which looks way cleaner and more professional.
However all of those things could've been a new branch with some clear documentation of this repository to make it much more easier and obvious the other devs to contribute. That's also my suggestion on how to gain more activity/progress in rewriting cp.

**Pull request merged**
