### PR TITLE
[wip] Added dutch language

### PR DESCRIPTION
**Pull request by finnie2006**
I added the dutch language, i hope u will add support for more strings in the project
Edit: also i dont see an option to select an language on the panel yet

### CODE REVIEW

**Comment by 1day2die** [comment]
did you just stop translating mid-file?

https://github.com/ControlPanel-gg/dashboard/pull/219/commits/0516ba360ac084375ff67e2076099ba03c06fea0

**Comment by finnie2006** [comment]
afbeelding

**Comment by finnie2006** [comment]
can it get merged?

**Comment by j122j** [comment]
This is only for laravel translations, maybe other languages can wait until we have a functional translations system?

@AVMG20 your opinion?

**Comment by finnie2006** [comment]
https://laravel.com/docs/8.x/localization
if u guys want i can do it using this

**Comment by 1day2die** [comment]
Next time please make Sure to create a PR to the development brach of dashboard ^^

**Comment by LogischJo** [comment]
As we don’t have any Translation system (like switching languages), I will make this into a draft.

**Comment by AVMG20** [comment]
Thanks for the effort; unfortunately, we don't have a functional translation system yet in place. This is something we which to work on :). luckily I'm dutch, so when I do get about adding more translation strings, I will use your pr :)

**Comment by 1day2die** [comment]
hi. if you still want to help with the translations, you can do so now.

https://github.com/ControlPanel-gg/dashboard/blob/1b6e059c99f0d9a7ef26c9aa4a0dd007c1a4688a/resources/lang/de.json

this is the german file.

You can just create a nl.json file and copy the structure from the de.json file to begin translating.
This would help us a lot :)

**Comment by finnie2006** [comment]
I started translate

**Comment by 1day2die** [comment]
whats your discord :)?

**Comment by 1day2die** [comment]
I will close this PR for now.
I would love it you create a new PR including a nl.json file for translations :)

If you need help, hit me up on our discord!

**Comment by finnie2006** [comment]
Why a new pr?

**Comment by 1day2die** [comment]
Because we need the translations in a very specific format.

Look here
https://github.com/ControlPanel-gg/dashboard/blob/1b6e059c99f0d9a7ef26c9aa4a0dd007c1a4688a/resources/lang/de.json

Hit me up on Discord if you got any more questions^^

**Pull request closed without merging**
