### PR TITLE
show number of referred people on profile page

### PR DESCRIPTION
**Pull request by ok236449**
It is just a small commit, but I am still quite new to Laravel/PHP. This is a big step for me XD.

image

### CODE REVIEW

**Comment by anondev-sudo** [comment]
Why this wasnt merged?

**Comment by 1day2die** [comment]
image

**Comment by 1day2die** [comment]
image

**Comment by anondev-sudo** [comment]
@ok236449 Please fiz

**Comment by ok236449** [comment]
Sorry, I don´t know how to add changes to an existing pull request. I created a new one by accident. #496

**Pull request closed without merging**
