### PR TITLE
Automatic Invoice Creation

### PR DESCRIPTION
**Pull request by 1day2die**
Sends an InvoicePDF per Mail to a User after successful credits purchase.

**_TO TEST THIS PR YOU NEED TO RUN_**
`sudo composer install --no-dev --optimize-autoloader`
and
`sudo php artisan migrate --force`

Ability to download all PDFs
Ability to set own Logo and Company Details
Features ongoing Invoice ID
Sorting per User per Year
Invoice Number Format: {PREFIX}-YEARMONTH000001
The last 6 digits of the invoice number are resetted every month

image

image

`@avmg please dont spank my ass i used PHPStorm to code this (ಥ﹏ಥ)`

### CODE REVIEW

**Comment by IceToast** [comment]
Hot

**Comment by IceToast** [comment]
Would love to see a Invoice overview by user or smth. 
Maybe on the "Show User" Page? Or a Invoice Datatable on which you could sort by users...

**Review by IceToast — CHANGES_REQUESTED** [review]
Nice Feature!
**Works:**
- Email attachment 
- Invoice creation 
- Invoice archive download

**Needs work:**
- Email text ("Your payment was processes!.")...
- Email field "Balance" should be rounded imo 
image
- Invoice PDF title -> weird/oldschool font
- Invoice Setting logo selection -> default are ".ico"-files -> should be .jpeg, .png for example

**Suggestion:**
- Invoice PDF field "PAID" -> color (PAID green for example)
- Invoice PDF field "User ID" -> why? would remove that
- Admin overview of all invoices by user or in a sortable table

**Comment by anondev-sudo** [comment]
There should be that users can see their paid invoices on dashboard too. For example add link to invoice pdf when you click on "Create payment" in audit log.

**Comment by IceToast** [comment]
> There should be that users can see their paid invoices on dashboard too. For example add link to invoice pdf when you click on "Create payment" in audit log.

You mean a overview of invoices for the user? I like the idea.

**Pull request merged**
