### PR TITLE
Installer script

### PR DESCRIPTION
**Pull request by 1day2die**

### CODE REVIEW

**Review by GoudronViande24 — APPROVED** [review]

**Comment by GoudronViande24** [comment]
Why is this not implemented ?

**Comment by 1day2die** [comment]
it is not done yet. It will be added on the next release

**Comment by GoudronViande24** [comment]
ok thank you! Is there an estimated delay ?

**Comment by 1day2die** [comment]
No. We are currently treating the dev branch and are then ready to release.  Maybe 1 or 2 weeks till release

**Comment by GoudronViande24** [comment]
Perfect, thank you!

**Pull request closed without merging**
