### PR TITLE
Discord Card and Re-Sync Button on Profile

### PR DESCRIPTION
**Pull request by 1day2die**
image

### CODE REVIEW

**Comment by 1day2die** [comment]
https://github.com/ControlPanel-gg/dashboard/issues/125

https://github.com/ControlPanel-gg/dashboard/issues/71

**Comment by LogischJo** [comment]
Is it possible to center the Discord card under the You are verified alert card?

**Comment by LogischJo** [comment]
But all in all an good and needed addition 👍

**Comment by 1day2die** [comment]
> Is it possible to center the Discord card under the You are verified alert card?

Of course you could, however when viewing the whole page, this layout looks actually better than centered imo

**Pull request merged**
